baseurl: "/energy-ses"
url: ""
title: "Energy SES"
description: "Energy Socioeconomic Study"

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore

sass:
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true